### ISSUE TITLE
./piano models/piano_model_vae_weights_02 file not found

### ISSUE THREAD

**Issue by AryanNanda17** [arman-aminian/lofi-generator#7]
After running python3 generate.py, getting this error:-
https://paste.debian.net/1302111/

**Comment by arman-aminian** [comment]
Hi there,

Thank you for reaching out and providing the details of the error you encountered. It appears that the issue might be related to the model not being trained for your specific use case. I recommend training the model on your own to tailor it to your needs.

Please use the "Variational Autoencoder - Piano Generator.ipynb" notebook for guidance on training the model. This notebook is designed to walk you through the process step-by-step, ensuring you can train the model effectively for generating piano music.

Make sure to follow the instructions within the notebook closely and install any required dependencies before starting. If you encounter any issues during the training process, please feel free to provide the details, and I'll be happy to assist further.

**Comment by AryanNanda17** [comment]
Hii, 
Thanks, Arman for your reply... 
The task that I am trying to achieve is non-stop Lofi music generation. There are many models that generate music for few seconds like MusicLm by Google and MusicGen by Meta, but they generate music of 10-20 seconds only. OpenAi's Jukebox generates music of long length but not nonstop and it takes a very long time to produce lengthy music so it is not feasible. 
I am currently working over an approach of recursively feeding the generated music of 10-20 sec to model to generate the next 10-20 sec music. But, I am not sure of this approach. What do you think about this?
